// DEPRECATED: Project list columns are now in config JSON (config.json or config-${RAILWAY_PROJECT_NAME}.json)
// under projectListColumns. This file is kept for reference only.
// /**
//  * Project List Table Configuration - CAPCO Design Group (default)
//  */

// import type { ProjectListColumnConfig } from "./project-list-table-config";

// export const PROJECT_LIST_COLUMNS: ProjectListColumnConfig[] = [
//   {
//     id: "delete",
//     label: "",
//     type: "delete",
//     allow: ["Admin", "Staff"],
//     width: 48,
//     icon: "trash",
//     tooltip: "Delete",
//   },
//   {
//     id: "edit",
//     label: "",
//     type: "edit",
//     width: 48,
//     icon: "edit",
//   },
//   {
//     id: "address",
//     label: "Address",
//     type: "text",
//     field: "address",
//     linkToProject: true,
//     width: 180,
//   },
//   {
//     id: "company",
//     label: "Company",
//     type: "company",
//     field: "authorProfile.companyName",
//     allow: ["Admin", "Staff"],
//     width: 120,
//   },
//   {
//     id: "status",
//     label: "Status",
//     type: "status",
//     field: "status",
//     width: 100,
//   },
//   {
//     id: "featured",
//     label: "",
//     type: "featured",
//     allow: ["Admin", "Staff"],
//     width: 80,
//     icon: "star",
//     tooltip: "Featured",
//   },
//   {
//     id: "files",
//     label: "Files",
//     type: "files",
//     displayProjectFiles: {
//       field: "projectFiles",
//       size: "sm",
//       tooltips: true,
//       emptyText: "No files",
//     },
//     width: 200,
//   },
//   {
//     id: "assigned",
//     label: "",
//     type: "assigned",
//     field: "assignedToId",
//     allow: ["Admin", "Staff"],
//     width: 100,
//     icon: "user",
//     tooltip: "Assigned To",
//   },
//   {
//     id: "progress",
//     label: "",
//     type: "progress",
//     field: "status",
//     width: 100,
//     icon: "percent",
//     tooltip: "Progress Thru Statuses",
//   },
//   {
//     id: "checklist",
//     label: "",
//     type: "checklist",
//     width: 80,
//     icon: "checklist",
//     tooltip: "Checklist",
//   },
//   {
//     id: "elapsed",
//     label: "",
//     type: "elapsed",
//     field: "createdAt",
//     width: 90,
//     icon: "calendar",
//     tooltip: "Elapsed Time",
//   },
//   {
//     id: "timeSince",
//     label: "",
//     type: "timeSince",
//     field: "updatedAt",
//     width: 110,
//     icon: "stopwatch",
//     tooltip: "Time since last status change",
//   },
//   {
//     id: "dueDate",
//     label: "",
//     type: "dueDate",
//     field: "dueDate",
//     width: 140,
//     allow: ["Admin", "Staff"],
//     icon: "calendar",
//     tooltip: "Due Date",
//   },
// ];
