-- Add featuredImageUrl column to projects table
ALTER TABLE projects ADD COLUMN IF NOT EXISTS featuredImageUrl text;

-- Add featured_image column if it doesn't exist (it should be an integer referencing files.id)
ALTER TABLE projects ADD COLUMN IF NOT EXISTS featured_image integer REFERENCES files(id);

-- Add comments for documentation
COMMENT ON COLUMN projects.featured_image IS 'ID of the featured image file from files table';
COMMENT ON COLUMN projects.featuredImageUrl IS 'Signed URL for the featured image (generated by application)';
