# GitGuardian configuration
# Ignore false positives from minified/bundled third-party JavaScript

version: 2

paths-ignore:
  # Booth component - third-party bundled JavaScript (minified)
  - src/components/booth/js/core.js
  - src/components/booth/js/tool.js
  - src/components/booth/css/main.css
  
  # Any other bundled/vendor files
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/*.min.js"
  - "**/*.bundle.js"

