services:
  calcom:
    image: calcom/cal.com:latest
    platform: linux/amd64
    container_name: calcom-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Database - Use local PostgreSQL
      DATABASE_URL: "postgresql://calcom:calcom_password@calcom-postgres:5432/calcom"
      DATABASE_DIRECT_URL: "postgresql://calcom:calcom_password@calcom-postgres:5432/calcom"
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: "your_nextauth_secret_here_change_this_in_production"

      # Required encryption key
      CALENDSO_ENCRYPTION_KEY: "your_encryption_key_here_change_this_in_production"

      # Webhook secret
      CAL_WEBHOOK_SECRET: "your_webhook_secret_here_change_this_in_production"

      # App configuration
      CALCOM_TELEMETRY_DISABLED: 1
      NODE_ENV: development

      # Disable email for local development
      EMAIL_SERVER_HOST: ""
      EMAIL_SERVER_PORT: ""
      EMAIL_SERVER_USER: ""
      EMAIL_SERVER_PASSWORD: ""
      EMAIL_FROM: ""

      # Twilio SMS Configuration for Cal.com SMS reminders
      TWILIO_ACCOUNT_SID: ""
      TWILIO_AUTH_TOKEN: ""
      TWILIO_PHONE_NUMBER: ""
      TWILIO_MESSAGING_SID: ""
      TWILIO_VERIFY_SID: ""

    volumes:
      - calcom_data:/app/data
    networks:
      - calcom-network
    depends_on:
      - calcom-postgres

  # Local PostgreSQL database for Cal.com
  calcom-postgres:
    image: postgres:15
    platform: linux/amd64
    container_name: calcom-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: calcom
      POSTGRES_USER: calcom
      POSTGRES_PASSWORD: calcom_password
    volumes:
      - calcom_postgres_data:/var/lib/postgresql/data
    networks:
      - calcom-network

  # Optional: Redis for caching
  redis:
    image: redis:7-alpine
    platform: linux/amd64
    container_name: calcom-redis
    restart: unless-stopped
    networks:
      - calcom-network

volumes:
  calcom_data:
  calcom_postgres_data:

networks:
  calcom-network:
    driver: bridge
