version: "3.8"

services:
  calcom:
    image: calcom/cal.com:latest
    platform: linux/amd64
    container_name: calcom-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Database - Use your existing Supabase PostgreSQL (URL-encoded password)
      DATABASE_URL: "postgresql://postgres:CxO%2FOgBSceiXcc1STDfpCLJdPI5A7rpQfsM%2BGEDewP0%3D@db.qudlxlryegnainztkrtk.supabase.co:5432/postgres"
      DATABASE_DIRECT_URL: "postgresql://postgres:CxO%2FOgBSceiXcc1STDfpCLJdPI5A7rpQfsM%2BGEDewP0%3D@db.qudlxlryegnainztkrtk.supabase.co:5432/postgres"
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}

      # Required encryption key
      CALENDSO_ENCRYPTION_KEY: ${CALENDSO_ENCRYPTION_KEY}

      # Webhook secret
      CAL_WEBHOOK_SECRET: ${CAL_WEBHOOK_SECRET}

      # App configuration
      CALCOM_TELEMETRY_DISABLED: 1
      NODE_ENV: production

      # Disable email for local development
      EMAIL_SERVER_HOST: ""
      EMAIL_SERVER_PORT: ""
      EMAIL_SERVER_USER: ""
      EMAIL_SERVER_PASSWORD: ""
      EMAIL_FROM: ""

    volumes:
      - calcom_data:/app/data
    networks:
      - calcom-network

  # Optional: Redis for caching
  redis:
    image: redis:7-alpine
    platform: linux/amd64
    container_name: calcom-redis
    restart: unless-stopped
    networks:
      - calcom-network

volumes:
  calcom_data:

networks:
  calcom-network:
    driver: bridge
