#!/bin/bash
echo "🔧 Quick Fix for Cal.com Environment Variables"
echo ""
echo "The app is failing because NEXTAUTH_SECRET is missing."
echo ""
echo "Go to Railway Dashboard → cal.com service → Variables tab"
echo ""
echo "Add these REQUIRED variables:"
echo ""
echo "1. NEXTAUTH_SECRET = 4tG5M8gnqIDmLLPW/ligvbxF7spOTbGxO3lYq4DXUjw="
echo "2. CALENDSO_ENCRYPTION_KEY = ScclPeosvzCw9WUasD1h46N13o0QSf4dpELWKfbK9po="
echo ""
echo "3. DATABASE_URL = (copy from Postgres service → Variables → DATABASE_URL)"
echo ""
echo "After adding these, Railway will auto-redeploy."
echo ""
echo "See fix-calcom-env-vars.md for complete variable list"
