#!/bin/bash

echo "🔧 Adding HTML MIME type support to Supabase storage bucket..."
echo ""
echo "Please run the following SQL in your Supabase dashboard:"
echo ""
echo "1. Go to your Supabase project dashboard"
echo "2. Navigate to SQL Editor"
echo "3. Copy and paste the contents of: sql-queriers/add-html-support-to-storage.sql"
echo "4. Click 'Run' to execute the SQL"
echo ""
echo "This will add support for HTML files in the project-media storage bucket."
echo "After running this SQL, your generated PDF documents will be saved to storage."
echo ""
echo "📁 SQL file location: sql-queriers/add-html-support-to-storage.sql"
