#!/bin/bash
# Quick setup instructions for Cal.com on Railway

echo "🚀 Cal.com Railway Setup Guide"
echo ""
echo "Since Railway can't find the calcom/cal.com repo directly, use one of these:"
echo ""
echo "OPTION 1: Use Railway Template (Recommended)"
echo "  1. Go to: https://railway.com/template/calcom"
echo "  2. Click 'Deploy on Railway'"
echo "  3. Select your project"
echo ""
echo "OPTION 2: Create Empty Service"
echo "  1. Railway Dashboard → + New → Empty Service"
echo "  2. Name: calcom-app"
echo "  3. Settings → Source → Connect GitHub"
echo "  4. Search: calcom/cal.com"
echo "  5. If not found, fork the repo to your GitHub first"
echo ""
echo "See setup-calcom-manual.md for detailed instructions"
