#!/usr/bin/env node

/**
 * Generate Version Script
 *
 * This script generates src/lib/version.ts with the current version and build date.
 * Run this automatically before each build to embed version info into the app.
 *
 * Usage: node scripts/generate-version.js
 */

const fs = require('fs');
const path = require('path');

// Read version from package.json
const packageJson = JSON.parse(
  fs.readFileSync(path.join(__dirname, '..', 'package.json'), 'utf-8')
);

const version = packageJson.version || '1.0.0';

// Generate build date in MMDDYYYY format
const now = new Date();
const month = String(now.getMonth() + 1).padStart(2, '0');
const day = String(now.getDate()).padStart(2, '0');
const year = now.getFullYear();
const buildDate = `${month}${day}${year}`;

// Full version string
const fullVersion = `v${version}-${buildDate}`;

// Generate the TypeScript file content
const content = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/generate-version.js at build time

export const APP_VERSION = '${version}';
export const BUILD_DATE = '${buildDate}';
export const FULL_VERSION = '${fullVersion}';
`;

// Write to src/lib/version.ts
const outputPath = path.join(__dirname, '..', 'src', 'lib', 'version.ts');
fs.writeFileSync(outputPath, content, 'utf-8');

console.log(`Generated version file: ${fullVersion}`);
