create table if not exists public."drawingLibraryItems" (
  id bigint generated by default as identity primary key,
  "projectId" integer references public.projects(id) on delete cascade,
  "authorId" uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  "imageUrl" text not null,
  "selectionShape" text not null default 'square',
  price numeric(10,2) not null default 0,
  priority integer not null default 1,
  dependencies jsonb not null default '[]'::jsonb,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create index if not exists "drawingLibraryItems_authorId_idx"
  on public."drawingLibraryItems" ("authorId");

create index if not exists "drawingLibraryItems_projectId_idx"
  on public."drawingLibraryItems" ("projectId");

create index if not exists "drawingLibraryItems_priority_idx"
  on public."drawingLibraryItems" (priority);

