-- Add featured_image_url column to projects table
ALTER TABLE projects ADD COLUMN IF NOT EXISTS featured_image_url text;

-- Add featured_image column if it doesn't exist (it should be an integer referencing files.id)
ALTER TABLE projects ADD COLUMN IF NOT EXISTS featured_image integer REFERENCES files(id);

-- Add comments for documentation
COMMENT ON COLUMN projects.featured_image IS 'ID of the featured image file from files table';
COMMENT ON COLUMN projects.featured_image_url IS 'Signed URL for the featured image (generated by application)';
