-- =====================================================
-- AI Document Generation System Schema
-- =====================================================
-- This migration adds AI-powered document generation capabilities
-- to the existing fire protection system
-- 
-- Run this in Supabase SQL Editor
-- =====================================================

-- Enable UUID extension (if not already enabled)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Document templates table
-- Stores templates for different types of fire protection documents
CREATE TABLE IF NOT EXISTS document_templates (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL,
  category TEXT NOT NULL, -- 'inspection', 'compliance', 'report', 'certification'
  description TEXT,
  "promptTemplate" TEXT NOT NULL, -- AI prompt template with placeholders
  fields JSONB NOT NULL DEFAULT '[]'::jsonb, -- Required fields schema
  "isActive" BOOLEAN DEFAULT true,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

-- AI-generated documents table
-- Stores documents generated by the AI agent
-- References existing projects table (using projectId as integer, not UUID)
CREATE TABLE IF NOT EXISTS ai_generated_documents (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "projectId" INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  "templateId" UUID REFERENCES document_templates(id),
  content TEXT NOT NULL, -- Generated document content
  "fileUrl" TEXT, -- Supabase Storage URL for PDF/export
  version INTEGER DEFAULT 1,
  metadata JSONB DEFAULT '{}'::jsonb,
  "authorId" UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

-- AI generation history table
-- Tracks all AI generations for cost analysis and auditing
CREATE TABLE IF NOT EXISTS ai_generations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "documentId" UUID REFERENCES ai_generated_documents(id) ON DELETE CASCADE,
  prompt TEXT NOT NULL,
  response TEXT NOT NULL,
  model TEXT NOT NULL, -- 'claude-3-opus', etc.
  "tokensUsed" INTEGER,
  "costEstimate" DECIMAL(10, 4), -- Estimated cost in USD
  "createdAt" TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_document_templates_category ON document_templates(category);
CREATE INDEX IF NOT EXISTS idx_document_templates_active ON document_templates("isActive");
CREATE INDEX IF NOT EXISTS idx_ai_documents_project_id ON ai_generated_documents("projectId");
CREATE INDEX IF NOT EXISTS idx_ai_documents_template_id ON ai_generated_documents("templateId");
CREATE INDEX IF NOT EXISTS idx_ai_documents_author_id ON ai_generated_documents("authorId");
CREATE INDEX IF NOT EXISTS idx_ai_generations_document_id ON ai_generations("documentId");
CREATE INDEX IF NOT EXISTS idx_ai_generations_created_at ON ai_generations("createdAt");

-- Row Level Security (RLS) Policies
ALTER TABLE document_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_generated_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_generations ENABLE ROW LEVEL SECURITY;

-- Document templates: Admins can manage, authenticated users can view active templates
CREATE POLICY "Admins can manage document templates"
  ON document_templates
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE id = auth.uid() AND role = 'Admin'
    )
  );

CREATE POLICY "Users can view active document templates"
  ON document_templates
  FOR SELECT
  TO authenticated
  USING ("isActive" = true);

-- AI-generated documents: Users can view documents for their own projects, Admins can view all
CREATE POLICY "Users can view own project documents"
  ON ai_generated_documents
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM projects
      WHERE projects.id = ai_generated_documents."projectId"
      AND (
        projects."authorId" = auth.uid()
        OR EXISTS (
          SELECT 1 FROM profiles
          WHERE id = auth.uid() AND role = 'Admin'
        )
      )
    )
  );

CREATE POLICY "Users can create documents for own projects"
  ON ai_generated_documents
  FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM projects
      WHERE projects.id = ai_generated_documents."projectId"
      AND (
        projects."authorId" = auth.uid()
        OR EXISTS (
          SELECT 1 FROM profiles
          WHERE id = auth.uid() AND role = 'Admin'
        )
      )
    )
  );

CREATE POLICY "Users can update own project documents"
  ON ai_generated_documents
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM projects
      WHERE projects.id = ai_generated_documents."projectId"
      AND (
        projects."authorId" = auth.uid()
        OR EXISTS (
          SELECT 1 FROM profiles
          WHERE id = auth.uid() AND role = 'Admin'
        )
      )
    )
  );

-- AI generations: Users can view generations for documents they can access
CREATE POLICY "Users can view own document generations"
  ON ai_generations
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM ai_generated_documents
      JOIN projects ON projects.id = ai_generated_documents."projectId"
      WHERE ai_generated_documents.id = ai_generations."documentId"
      AND (
        projects."authorId" = auth.uid()
        OR EXISTS (
          SELECT 1 FROM profiles
          WHERE id = auth.uid() AND role = 'Admin'
        )
      )
    )
  );

-- Updated_at trigger function (if not already exists)
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updatedAt" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply updated_at triggers
DROP TRIGGER IF EXISTS update_document_templates_updated_at ON document_templates;
CREATE TRIGGER update_document_templates_updated_at
  BEFORE UPDATE ON document_templates
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_ai_documents_updated_at ON ai_generated_documents;
CREATE TRIGGER update_ai_documents_updated_at
  BEFORE UPDATE ON ai_generated_documents
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Insert sample document templates
INSERT INTO document_templates (name, category, description, "promptTemplate", fields) VALUES
(
  'Fire Safety Inspection Report',
  'inspection',
  'Comprehensive fire safety inspection report',
  'Generate a fire safety inspection report for {{facility_name}}. Address: {{address}}. Inspection date: {{inspection_date}}. Include findings, violations, and recommendations.',
  '["facility_name", "address", "inspection_date", "inspector_name"]'::jsonb
),
(
  'NFPA Compliance Certificate',
  'certification',
  'NFPA standards compliance certification',
  'Generate an NFPA compliance certificate for {{facility_name}} certifying compliance with {{nfpa_standard}}. Valid until {{expiry_date}}.',
  '["facility_name", "nfpa_standard", "expiry_date", "certifying_officer"]'::jsonb
),
(
  'Fire Protection System Design Report',
  'report',
  'Detailed fire protection system design documentation',
  'Generate a comprehensive fire protection system design report for {{project_name}} located at {{address}}. Include system specifications, code compliance, and installation requirements.',
  '["project_name", "address", "system_type", "design_date"]'::jsonb
)
ON CONFLICT DO NOTHING;

-- Grant necessary permissions
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT ALL ON document_templates TO authenticated;
GRANT ALL ON ai_generated_documents TO authenticated;
GRANT ALL ON ai_generations TO authenticated;

-- =====================================================
-- Migration Complete
-- =====================================================
-- Tables created:
--   - document_templates (templates for AI generation)
--   - ai_generated_documents (generated documents)
--   - ai_generations (generation history and cost tracking)
--
-- RLS policies configured for:
--   - Admin full access
--   - Users can access their own project documents
--
-- Sample templates inserted for immediate use
-- =====================================================

